export const styles = {
  section: { marginBottom: '1.25rem' },
  sectionTitle: { fontSize: '1rem', fontWeight: 600, margin: '0 0 0.25rem 0' },
  sectionDesc: { fontSize: '0.875rem', color: '#64748b', margin: '0 0 0.75rem 0' },
  field: { marginBottom: '0.75rem' },
  label: { display: 'block', fontSize: '0.875rem', fontWeight: 500, marginBottom: '0.25rem' },
  input: {
    width: '100%',
    padding: '0.5rem 0.75rem',
    border: '1px solid #e2e8f0',
    borderRadius: 6,
    fontSize: '0.875rem',
  },
  textarea: {
    width: '100%',
    padding: '0.5rem 0.75rem',
    border: '1px solid #e2e8f0',
    borderRadius: 6,
    fontSize: '0.875rem',
    minHeight: '4rem',
    resize: 'vertical' as const,
  },
  select: { padding: '0.5rem 0.75rem', border: '1px solid #e2e8f0', borderRadius: 6, fontSize: '0.875rem', minWidth: '10rem' },
  radioGroup: { display: 'flex', flexWrap: 'wrap' as const, gap: '0.75rem' },
  checkboxGroup: { display: 'flex', flexWrap: 'wrap' as const, gap: '0.75rem' },
  radio: { display: 'inline-flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.875rem', cursor: 'pointer' },
  checkbox: { display: 'inline-flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.875rem', cursor: 'pointer' },
  btn: { padding: '0.5rem 1rem', fontSize: '0.875rem', fontWeight: 500, borderRadius: 6, cursor: 'pointer', border: '1px solid transparent' },
  btnPrimary: { background: '#0f172a', color: '#fff', borderColor: '#0f172a' },
  btnSecondary: { background: '#fff', color: '#334155', borderColor: '#e2e8f0' },
  errors: { background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 6, padding: '0.75rem 1rem', marginBottom: '1rem' },
  errorsList: { margin: 0, paddingLeft: '1.25rem', color: '#dc2626' },
  actions: { display: 'flex', flexWrap: 'wrap' as const, gap: '0.5rem', paddingTop: '1rem', borderTop: '1px solid #e2e8f0' },
  preview: { border: '1px solid #e2e8f0', borderRadius: 8, padding: '1rem', background: '#f8fafc' },
  previewTabs: { display: 'flex', gap: '0.25rem', marginBottom: '0.75rem' },
  previewTab: { padding: '0.35rem 0.75rem', fontSize: '0.8125rem', border: '1px solid #e2e8f0', background: '#fff', borderRadius: 4, cursor: 'pointer' },
  previewTabActive: { background: '#0f172a', color: '#fff', borderColor: '#0f172a' },
  previewDevice: { background: '#fff', borderRadius: 8, padding: '1rem', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  previewTitle: { fontWeight: 600, marginBottom: '0.25rem' },
  previewBody: { color: '#475569', lineHeight: 1.4 },
  accordion: { border: '1px solid #e2e8f0', borderRadius: 6, marginBottom: '1.25rem' },
  accordionSummary: { padding: '0.75rem 1rem', fontWeight: 500, cursor: 'pointer' },
  accordionBody: { padding: '0 1rem 1rem', borderTop: '1px solid #e2e8f0' },
  counter: { fontWeight: 400, color: '#64748b', marginLeft: '0.25rem' },
  counterWarn: { color: '#dc2626' },
  reach: { fontSize: '0.875rem', color: '#64748b', marginTop: '0.5rem' },
  variableList: { listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexWrap: 'wrap' as const, gap: '0.5rem' },
  variableCode: { fontSize: '0.8125rem', padding: '0.2rem 0.5rem', background: '#f1f5f9', borderRadius: 4 },
  hint: { fontSize: '0.8125rem', color: '#64748b', margin: '0 0 0.5rem 0' },
};
